### ISSUE TITLE
Overlapping UBC banner

### ISSUE THREAD

**Issue by stephan-koenig** [ubc-cpsc/jekyll-clf-theme#2]
Hi,

A part of the UBC banner is duplicated, leading to a 404 page.

![Duplicate banner](https://user-images.githubusercontent.com/11433347/217909984-d0dfa820-69fe-4e7b-9fb4-9ec00e182064.png)

**Comment by joelpittet** [comment]
Thanks @stephan-koenig I'll look into fixing that

**Comment by joelpittet** [comment]
@stephan-koenig They removed that spot in the latest CLF, it used to be where it said "A place of mind", I removed it from the header template and adjusted the banner to fill the space. Also I removed the "Vancouver Campus" byline because there is no reason to hard code that in there. Hope that works for you?

A `bundle update` will do the trick though I'll commit a new gemfile.lock over on the other project

**Comment by stephan-koenig** [comment]
Works for me and looks good! Thanks!
